name: 'Create Module'
description: 'Action to create an automation module from one of the availble templates'
author: 'Your name or organization here'
inputs:
  token:
    required: true
    description: GitHub token with the access necessary to provision a new repository in the target org
  type:
    required: true
    description: the type of module (terraform or gitops)
  name:
    required: true
    description: The name of the new repository that will be created
  displayName:
    required: false
    description: The display name of the new repository that will be created
  provider:
    required: false
    description: The cloud provider this module will work against
  softwareProvider:
    required: false
    description: The software provider for this module
  owner:
    required: true
    description: The github organization where the new repository should be created
    default: cloud-native-toolkit
  strict:
    required: false
    description: Flag that if value is true with throw an error if the repo already exists. If false then the existing repo will be (re-)configured
    default: true
outputs:
  repo_url:
    description: The url of the created repository
  repoUrl:
    description: The url of the created repository
  owner:
    description: The owner of the repo
  repo:
    description: The name of the repo
  moduleName:
    description: The name of the module
  displayName:
    description: The display name of the module
  cloudProvider:
    description: The cloud provider, if applicable, for the module. (E.g. ibm, aws, azure)
  softwareProvider:
    description: The provider of the software that will be installed into a cluster, if applicable. (E.g. ibm-cp)
runs:
  using: 'node12'
  main: 'dist/index.js'
